### ISSUE TITLE
Not able to set attribute name to tooltipster="top"

### ISSUE THREAD

**Issue by jacobplumb** [maciejsaw/tooltipster-for-webflow#1]
Hi Maciej,

Looks like Webflow has maybe removed the ability to include '=' signs in attribute names?

<img width="234" alt="screen shot 2017-02-13 at 11 44 21" src="https://cloud.githubusercontent.com/assets/25655990/22875663/420f802a-f210-11e6-9f27-daa979be8b08.png">

Or maybe I'm just doing something wrong?

Thanks,

Jacob

**Comment by maciejsaw** [comment]
You need to enter "tooltipster" as title and "top" as value.

**Comment by jacobplumb** [comment]
Ah, got it! Thanks so much.
